'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmNonConProduct
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory_Shaili.frmNonConProduct", GetType(frmNonConProduct).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmbReason_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmbReason.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmbReason_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmbReason.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmbReason_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmbReason.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdcancel_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdcancel.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdcancel_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdcancel.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdcancel_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdcancel.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdsave_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdsave.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdsave_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdsave.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdsave_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdsave.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property dtComplain_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("dtComplain.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property dtComplain_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("dtComplain.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property dtComplain_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("dtComplain.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpDispose_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDispose.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property grpDispose_DrawGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDispose.DrawGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=8, Height=8}.
    '''</summary>
    Friend Shared ReadOnly Property grpDispose_GridSize() As System.Drawing.Size
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDispose.GridSize", resourceCulture)
            Return CType(obj,System.Drawing.Size)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property grpDispose_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDispose.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpDispose_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDispose.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property grpDispose_SnapToGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("grpDispose.SnapToGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblAction_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblAction.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblAction_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblAction.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblAction_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblAction.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCompNo_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCompNo.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblCompNo_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCompNo.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCompNo_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCompNo.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCustName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCustName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblCustName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCustName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCustName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCustName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblItemName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblItemName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblItemName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblItemName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblItemName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblItemName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblItemSrNo_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblItemSrNo.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblItemSrNo_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblItemSrNo.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblItemSrNo_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblItemSrNo.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblMake_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblMake.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblMake_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblMake.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblMake_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblMake.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblProduct_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblProduct.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblProduct_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblProduct.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblProduct_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblProduct.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblQty_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblQty.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblQty_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblQty.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblQty_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblQty.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblReason_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblReason.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblReason_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblReason.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblReason_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblReason.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblRemark_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblRemark.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblRemark_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblRemark.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblRemark_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblRemark.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupItemName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupItemName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lkupItemName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupItemName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupItemName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupItemName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupSuppName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupSuppName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lkupSuppName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupSuppName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupSuppName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupSuppName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtAction_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtAction.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtAction_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtAction.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtAction_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtAction.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtCompNo_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtCompNo.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtCompNo_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtCompNo.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtCompNo_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtCompNo.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtItemSrNo_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtItemSrNo.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtItemSrNo_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtItemSrNo.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtItemSrNo_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtItemSrNo.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtMake_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtMake.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtMake_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtMake.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtMake_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtMake.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtQty_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtQty.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtQty_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtQty.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtQty_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtQty.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtRemark_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRemark.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtRemark_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRemark.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtRemark_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRemark.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSrNo_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSrNo.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSrNo_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSrNo.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSrNo_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSrNo.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
End Class
