'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmRM_Opening_Stock
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory_Shaili.frmRM_Opening_Stock", GetType(frmRM_Opening_Stock).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdcancel_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdcancel.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdcancel_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdcancel.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdcancel_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdcancel.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdsave_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdsave.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdsave_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdsave.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdsave_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdsave.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property dtpdate_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("dtpdate.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property dtpdate_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("dtpdate.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property dtpdate_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("dtpdate.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property GroupControl1_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupControl1.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property GroupControl1_DrawGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupControl1.DrawGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=8, Height=8}.
    '''</summary>
    Friend Shared ReadOnly Property GroupControl1_GridSize() As System.Drawing.Size
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupControl1.GridSize", resourceCulture)
            Return CType(obj,System.Drawing.Size)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property GroupControl1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupControl1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property GroupControl1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupControl1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property GroupControl1_SnapToGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupControl1.SnapToGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblDate_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblDate.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblDate_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblDate.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblDate_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblDate.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblInQty_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblInQty.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblInQty_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblInQty.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblInQty_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblInQty.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblProdName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblProdName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblProdName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblProdName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblProdName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblProdName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblUnit_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblUnit.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblUnit_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblUnit.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblUnit_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblUnit.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblVINO_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblVINO.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblVINO_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblVINO.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblVINO_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblVINO.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lkupName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtID_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtID.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtID_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtID.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtID_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtID.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtQty_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtQty.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtQty_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtQty.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtQty_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtQty.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtRMUnit_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRMUnit.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtRMUnit_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRMUnit.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtRMUnit_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRMUnit.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtRMVINO_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRMVINO.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtRMVINO_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRMVINO.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtRMVINO_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtRMVINO.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
End Class
