'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class FrmSupplier
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory_Shaili.FrmSupplier", GetType(FrmSupplier).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmbRMItem_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmbRMItem.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmbRMItem_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmbRMItem.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmbRMItem_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmbRMItem.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdAdd_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdAdd.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdAdd_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdAdd.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdAdd_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdAdd.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdAddGroup_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdAddGroup.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdAddGroup_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdAddGroup.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdAddGroup_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdAddGroup.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdClose_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdClose.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdClose_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdClose.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdClose_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdClose.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdDelete_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdDelete.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdDelete_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdDelete.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdDelete_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdDelete.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdSave_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdSave.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property cmdSave_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdSave.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property cmdSave_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("cmdSave.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property gdSupplier_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("gdSupplier.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property gdSupplier_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("gdSupplier.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property gdSupplier_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("gdSupplier.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpSupplier_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpSupplier.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property grpSupplier_DrawGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("grpSupplier.DrawGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=8, Height=8}.
    '''</summary>
    Friend Shared ReadOnly Property grpSupplier_GridSize() As System.Drawing.Size
        Get
            Dim obj As Object = ResourceManager.GetObject("grpSupplier.GridSize", resourceCulture)
            Return CType(obj,System.Drawing.Size)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property grpSupplier_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("grpSupplier.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property grpSupplier_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("grpSupplier.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property grpSupplier_SnapToGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("grpSupplier.SnapToGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property gvSupplier_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("gvSupplier.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property gvSupplier_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("gvSupplier.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblAdd_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblAdd.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblAdd_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblAdd.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblAdd_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblAdd.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCity_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCity.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblCity_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCity.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblCity_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblCity.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblcst_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblcst.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblcst_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblcst.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblcst_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblcst.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblExcise_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblExcise.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblExcise_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblExcise.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblExcise_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblExcise.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblGroup_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblGroup.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblGroup_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblGroup.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblGroup_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblGroup.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblGst_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblGst.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblGst_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblGst.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblGst_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblGst.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblMobile_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblMobile.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblMobile_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblMobile.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblMobile_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblMobile.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblPhone_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPhone.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblPhone_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPhone.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblPhone_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPhone.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblPin_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPin.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblPin_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPin.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblPin_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblPin.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblRaw_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblRaw.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblRaw_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblRaw.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblRaw_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblRaw.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblSuppID_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblSuppID.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblSuppID_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblSuppID.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblSuppID_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblSuppID.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblSuppName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblSuppName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lblSuppName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lblSuppName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lblSuppName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lblSuppName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupSuppGroup_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupSuppGroup.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property lkupSuppGroup_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupSuppGroup.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property lkupSuppGroup_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("lkupSuppGroup.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property pnlItem_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("pnlItem.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property pnlItem_DrawGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("pnlItem.DrawGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=8, Height=8}.
    '''</summary>
    Friend Shared ReadOnly Property pnlItem_GridSize() As System.Drawing.Size
        Get
            Dim obj As Object = ResourceManager.GetObject("pnlItem.GridSize", resourceCulture)
            Return CType(obj,System.Drawing.Size)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property pnlItem_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("pnlItem.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property pnlItem_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("pnlItem.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property pnlItem_SnapToGrid() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("pnlItem.SnapToGrid", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppAdd_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppAdd.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppAdd_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppAdd.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppAdd_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppAdd.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppCity_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppCity.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppCity_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppCity.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppCity_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppCity.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppCST_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppCST.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppCST_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppCST.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppCST_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppCST.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppExcise_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppExcise.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppExcise_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppExcise.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppExcise_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppExcise.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppGST_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppGST.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppGST_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppGST.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppGST_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppGST.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppId_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppId.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppId_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppId.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppId_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppId.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppMobile_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppMobile.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppMobile_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppMobile.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppMobile_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppMobile.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppName_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppName.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppName_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppName.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppName_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppName.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppPhone_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppPhone.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppPhone_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppPhone.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppPhone_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppPhone.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppPin_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppPin.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppPin_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppPin.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property txtSuppPin_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("txtSuppPin.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
End Class
