'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class rptChallanRecall
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory_Shaili.rptChallanRecall", GetType(rptChallanRecall).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Detail_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Detail.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Detail_Expanded() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Detail.Expanded", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property Detail_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("Detail.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property Detail_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Detail.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property PageFooter_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("PageFooter.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property PageFooter_Expanded() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("PageFooter.Expanded", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
    '''</summary>
    Friend Shared ReadOnly Property PageFooter_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("PageFooter.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property PageFooter_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("PageFooter.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property PageHeader_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("PageHeader.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property PageHeader_Expanded() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("PageHeader.Expanded", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
    '''</summary>
    Friend Shared ReadOnly Property PageHeader_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("PageHeader.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property PageHeader_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("PageHeader.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel1_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel1.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel1_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel1.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel12_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel12.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel12_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel12.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel12_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel12.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel13_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel13.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel13_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel13.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel13_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel13.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel14_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel14.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel14_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel14.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel14_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLabel14.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLine1_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine1.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLine1_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine1.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLine1_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine1.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLine2_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine2.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLine2_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine2.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLine2_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine2.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLine3_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine3.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrLine3_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine3.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrLine3_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrLine3.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTable3_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTable3.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTable3_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTable3.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrTable3_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTable3.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell7_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell7.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell7_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell7.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell7_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell7.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell8_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell8.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell8_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell8.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell8_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell8.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell9_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell9.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell9_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell9.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell9_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableCell9.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow3_DefaultModifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableRow3.DefaultModifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow3_Modifiers() As System.CodeDom.MemberAttributes
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableRow3.Modifiers", resourceCulture)
            Return CType(obj,System.CodeDom.MemberAttributes)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to False.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow3_UserDesignerLocked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("XrTableRow3.UserDesignerLocked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
End Class
