'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class rptMIS
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory_Shaili.rptMIS", GetType(rptMIS).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Detail.
    '''</summary>
    Friend Shared ReadOnly Property Detail_Name() As String
        Get
            Return ResourceManager.GetString("Detail.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GroupHeader1.
    '''</summary>
    Friend Shared ReadOnly Property GroupHeader1_Name() As String
        Get
            Return ResourceManager.GetString("GroupHeader1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PageFooter.
    '''</summary>
    Friend Shared ReadOnly Property PageFooter_Name() As String
        Get
            Return ResourceManager.GetString("PageFooter.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PageHeader.
    '''</summary>
    Friend Shared ReadOnly Property PageHeader_Name() As String
        Get
            Return ResourceManager.GetString("PageHeader.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel1.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel1_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel10.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel10_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel10.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel11.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel11_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel11.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel12.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel12_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel12.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel13.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel13_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel13.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel14.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel14_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel14.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel15.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel15_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel15.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel16.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel16_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel16.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel2.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel2_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel3.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel3_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel3.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel4.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel4_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel4.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel5.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel5_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel5.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel6.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel6_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel6.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel7.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel7_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel7.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel8.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel8_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel8.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel9.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel9_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel9.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTable1.
    '''</summary>
    Friend Shared ReadOnly Property XrTable1_Name() As String
        Get
            Return ResourceManager.GetString("XrTable1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTable2.
    '''</summary>
    Friend Shared ReadOnly Property XrTable2_Name() As String
        Get
            Return ResourceManager.GetString("XrTable2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell1.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell1_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell10.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell10_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell10.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell2.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell2_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell3.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell3_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell3.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell4.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell4_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell4.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell5.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell5_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell5.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell6.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell6_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell6.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell7.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell7_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell7.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell8.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell8_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell8.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell9.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell9_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell9.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableRow1.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow1_Name() As String
        Get
            Return ResourceManager.GetString("XrTableRow1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableRow2.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow2_Name() As String
        Get
            Return ResourceManager.GetString("XrTableRow2.Name", resourceCulture)
        End Get
    End Property
End Class
