'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class rptOrder
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory_Shaili.rptOrder", GetType(rptOrder).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Detail.
    '''</summary>
    Friend Shared ReadOnly Property Detail_Name() As String
        Get
            Return ResourceManager.GetString("Detail.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GroupHeader1.
    '''</summary>
    Friend Shared ReadOnly Property GroupHeader1_Name() As String
        Get
            Return ResourceManager.GetString("GroupHeader1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PageFooter.
    '''</summary>
    Friend Shared ReadOnly Property PageFooter_Name() As String
        Get
            Return ResourceManager.GetString("PageFooter.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PageHeader.
    '''</summary>
    Friend Shared ReadOnly Property PageHeader_Name() As String
        Get
            Return ResourceManager.GetString("PageHeader.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel1.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel1_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel10.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel10_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel10.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel11.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel11_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel11.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel12.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel12_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel12.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel13.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel13_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel13.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel14.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel14_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel14.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel15.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel15_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel15.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel16.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel16_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel16.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel17.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel17_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel17.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel18.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel18_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel18.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel19.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel19_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel19.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel2.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel2_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel20.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel20_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel20.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel21.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel21_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel21.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel22.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel22_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel22.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel23.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel23_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel23.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel24.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel24_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel24.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel25.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel25_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel25.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel26.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel26_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel26.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel27.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel27_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel27.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel28.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel28_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel28.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel29.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel29_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel29.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel3.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel3_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel3.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel31.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel31_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel31.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel32.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel32_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel32.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel34.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel34_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel34.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel35.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel35_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel35.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel36.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel36_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel36.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel37.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel37_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel37.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel38.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel38_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel38.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel39.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel39_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel39.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel4.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel4_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel4.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel40.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel40_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel40.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel41.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel41_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel41.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel42.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel42_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel42.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel5.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel5_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel5.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel6.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel6_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel6.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel7.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel7_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel7.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel8.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel8_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel8.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLabel9.
    '''</summary>
    Friend Shared ReadOnly Property XrLabel9_Name() As String
        Get
            Return ResourceManager.GetString("XrLabel9.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine1.
    '''</summary>
    Friend Shared ReadOnly Property XrLine1_Name() As String
        Get
            Return ResourceManager.GetString("XrLine1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine10.
    '''</summary>
    Friend Shared ReadOnly Property XrLine10_Name() As String
        Get
            Return ResourceManager.GetString("XrLine10.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine11.
    '''</summary>
    Friend Shared ReadOnly Property XrLine11_Name() As String
        Get
            Return ResourceManager.GetString("XrLine11.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine12.
    '''</summary>
    Friend Shared ReadOnly Property XrLine12_Name() As String
        Get
            Return ResourceManager.GetString("XrLine12.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine13.
    '''</summary>
    Friend Shared ReadOnly Property XrLine13_Name() As String
        Get
            Return ResourceManager.GetString("XrLine13.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine14.
    '''</summary>
    Friend Shared ReadOnly Property XrLine14_Name() As String
        Get
            Return ResourceManager.GetString("XrLine14.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine15.
    '''</summary>
    Friend Shared ReadOnly Property XrLine15_Name() As String
        Get
            Return ResourceManager.GetString("XrLine15.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine16.
    '''</summary>
    Friend Shared ReadOnly Property XrLine16_Name() As String
        Get
            Return ResourceManager.GetString("XrLine16.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine2.
    '''</summary>
    Friend Shared ReadOnly Property XrLine2_Name() As String
        Get
            Return ResourceManager.GetString("XrLine2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine3.
    '''</summary>
    Friend Shared ReadOnly Property XrLine3_Name() As String
        Get
            Return ResourceManager.GetString("XrLine3.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine4.
    '''</summary>
    Friend Shared ReadOnly Property XrLine4_Name() As String
        Get
            Return ResourceManager.GetString("XrLine4.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine5.
    '''</summary>
    Friend Shared ReadOnly Property XrLine5_Name() As String
        Get
            Return ResourceManager.GetString("XrLine5.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine6.
    '''</summary>
    Friend Shared ReadOnly Property XrLine6_Name() As String
        Get
            Return ResourceManager.GetString("XrLine6.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine7.
    '''</summary>
    Friend Shared ReadOnly Property XrLine7_Name() As String
        Get
            Return ResourceManager.GetString("XrLine7.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine8.
    '''</summary>
    Friend Shared ReadOnly Property XrLine8_Name() As String
        Get
            Return ResourceManager.GetString("XrLine8.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrLine9.
    '''</summary>
    Friend Shared ReadOnly Property XrLine9_Name() As String
        Get
            Return ResourceManager.GetString("XrLine9.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTable1.
    '''</summary>
    Friend Shared ReadOnly Property XrTable1_Name() As String
        Get
            Return ResourceManager.GetString("XrTable1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTable2.
    '''</summary>
    Friend Shared ReadOnly Property XrTable2_Name() As String
        Get
            Return ResourceManager.GetString("XrTable2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell10.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell10_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell10.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell2.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell2_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell2.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell3.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell3_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell3.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell4.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell4_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell4.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell5.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell5_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell5.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell6.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell6_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell6.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell8.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell8_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell8.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableCell9.
    '''</summary>
    Friend Shared ReadOnly Property XrTableCell9_Name() As String
        Get
            Return ResourceManager.GetString("XrTableCell9.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableRow1.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow1_Name() As String
        Get
            Return ResourceManager.GetString("XrTableRow1.Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XrTableRow2.
    '''</summary>
    Friend Shared ReadOnly Property XrTableRow2_Name() As String
        Get
            Return ResourceManager.GetString("XrTableRow2.Name", resourceCulture)
        End Get
    End Property
End Class
